# Generated by Django 4.1 on 2022-10-31 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_follow_follower_alter_follow_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('chat_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chat', to='accounts.profile')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('msg_content', models.TextField()),
                ('msg_sender', models.CharField(choices=[('msgsender', 'MsgSender'), ('msgreceiver', 'MsgReceiver')], max_length=11)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='message.chat')),
            ],
        ),
    ]
