# Generated by Django 4.1 on 2022-08-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_post_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='hello', max_length=400),
            preserve_default=False,
        ),
    ]
