# Generated by Django 4.1 on 2022-09-19 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
