# Generated by Django 4.1 on 2022-10-18 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0009_alter_blogcomment_comment_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('like_auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('like_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_likes', to='blogs.blogpost')),
            ],
        ),
    ]
