# Generated by Django 4.1 on 2022-10-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_bloglike'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='num_count',
            field=models.IntegerField(default=0),
        ),
    ]
