# Generated by Django 4.1 on 2022-10-18 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_blogpost_num_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='num_count',
            new_name='num_of_likes',
        ),
    ]
