# Generated by Django 4.1 on 2022-10-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
